### ISSUE TITLE
Pip install fra poetry's requirements.txt export

### ISSUE THREAD

**Issue by iSplasher** [aarhusstadsarkiv/stadsarkiv-client#15]
Hej, du husker det måske ikke, men jeg snakkede om det her.
Med Poetry, kan du eksportere en `requirements.txt` fil og stadig bibeholde `pip install -r requirements.txt`:
```sh
# efter man har git clone'et projektet
poetry export --format=requirements.txt -o requirements.txt
pip install -r requirements.txt
```
#### Hvad får vi ud af dette?
- Lægges pakkerne i poetry, får vi `poetry.lock` der sørger for deterministiske og låste afhængigheder (især vigtigt i CI)
- Poetry eksportere en requirements.txt fil som også inkludere pakkernes sha256 hash værdier (som også er i `poetry.lock` filen), hvilket er vigtigt i forhold til troværdigheden af pakken.

#### Hvad kræver dette?
Ovenstående vil ikke virke ligenu fordi `pyproject.toml` filen ikke har afhængighederne. Derfor bør pakkerne i `requirements.txt` flyttes ind til `pyproject.toml` først, og derefter slettes. Dette kan hurtigt gøres således:
- Først, kopier følgende ind i `pyproject.toml`, ellers vil `poetry` kommandoer ikke virke:
```toml
[tool.poetry]
name = "stadsarkiv-client"
version = "0.1.0"
description = ""
authors = ["Navn <email@email.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
- Nu kan du tilføje pakkerne fra requirements.txt med `poetry add $(cat .\requirements.txt) `
> Poetry vil allerede se at de er installeret, hvis du tidligere har kørt `pip install -r requirements.txt` i en virtualenv.

Efterfølgende vil dette virke:
```
poetry export --format=requirements.txt -o requirements.txt
pip install -r requirements.txt
```

**Hvis du siger god for det, har jeg ikke noget i mod at lave en PR**
