### ISSUE TITLE
The settings-file should use standard yml-format everywhere

### ISSUE THREAD

**Issue by clausjuhl** [aarhusstadsarkiv/stadsarkiv-client#288]
```yaml
main_menu_sections:
  - name: guides
    title: Vejledninger
    pages:
      - name: page_searchguide
        title: Hjælp til søgning
  - name: about
  ...
```

instead of

```yaml
main_menu_sections:
  - name: guides
    title: Vejledninger
    pages:
      - {name: page_searchguide, title: Hjælp til søgning}
  - name: about
  ...
```
